name = "epiphany"
main = "dist/server/server.js"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NEWSLETTER_FROM_EMAIL = "info@acehou.org"
NEWSLETTER_FROM_NAME = "Anglican Church of the Epiphany, Houston"

[triggers]
crons = [ "*/5 * * * *", "15 8 * * *" ]

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "epiphany-db"
database_id = "842c4a1e-3495-4387-8275-168bc15fb78e"
migrations_dir = "migrations"
