INSERT INTO ministries (
  id,
  slug,
  name,
  summary,
  description,
  image_alt,
  display_order,
  status,
  published_at,
  created_at,
  updated_at
) VALUES
  (
    'ministry-children',
    'children',
    'Children''s Ministry',
    'Nurturing young hearts in the love of Christ through Bible stories, music, and creative play.',
    'The Children’s Ministry is a vibrant and nurturing environment where young hearts are introduced to the love of Jesus Christ. Through Bible lessons, worship, fellowship, and engaging activities, we help children grow in faith, character, and understanding of God’s Word. Our desire is to raise a generation that knows God, loves Him, and follows Him faithfully throughout their lives. We warmly welcome every child to discover the joy of belonging to God’s family.',
    'Children participating in church ministry',
    10,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  ),
  (
    'ministry-youth',
    'youth',
    'Youth Ministry',
    'Equipping youths to live boldly for Christ.',
    'The Youth Ministry is dedicated to empowering young people to develop a strong and personal relationship with Jesus Christ. In a world filled with challenges and opportunities, we provide spiritual guidance, fellowship, mentorship, and opportunities for service. We encourage our youth to embrace their God-given purpose, live boldly for Christ, and become positive influences in their families, schools, communities, and beyond.',
    'Young people growing together in faith',
    20,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  ),
  (
    'ministry-men',
    'mens',
    'Men''s Fellowship',
    'Building brotherhood through scripture, prayer, and shared mission.',
    'The Men’s Fellowship is a brotherhood of Christian men committed to growing in faith, leadership, and service. We strive to strengthen one another through prayer, Bible study, fellowship, and practical support. As men of God, we seek to be faithful leaders in our homes, church, workplace, and community, reflecting the character and love of Christ in all we do.',
    'Members of the men’s fellowship',
    30,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  ),
  (
    'ministry-women',
    'womens',
    'Women''s Fellowship',
    'A vibrant community of women growing together in faith and friendship.',
    'The Women’s Fellowship is a caring and empowering community where women come together to grow spiritually, build meaningful relationships, and serve God with passion. Through prayer, fellowship, Bible study, and outreach, we encourage one another to fulfill God’s purpose in our lives. We celebrate the unique gifts and calling of every woman and seek to make a lasting impact for Christ in our families, church, and society.',
    'Members of the women’s fellowship',
    40,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  ),
  (
    'ministry-prayer',
    'prayer',
    'Prayer Ministry',
    'Interceding for our church, city, and world.',
    'The Prayer Ministry stands at the heart of the church’s spiritual life, believing that prayer is the key to experiencing God’s presence, power, and guidance. We are committed to interceding for the church, our families, our community, and the world. Through faithful prayer, we seek God’s will, strengthen believers, and witness His transforming work in every area of life. We invite all who desire a deeper prayer life to join us in this vital ministry.',
    'Church members gathered in prayer',
    50,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  ),
  (
    'ministry-choir',
    'choir',
    'Choir Ministry',
    'Leading the congregation in worship through sacred music.',
    'The Choir Ministry is a dedicated team of worshippers called to glorify God through music and song. Through heartfelt praise and worship, we lead the congregation into God’s presence and proclaim His greatness. Our ministry seeks not only musical excellence but also spiritual devotion, using our gifts to inspire faith, encourage believers, and draw hearts closer to God. Every song we sing is an offering of worship to our Lord and Savior.',
    'The choir leading worship',
    60,
    'published',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z',
    '2026-09-02T00:00:00.000Z'
  )
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  summary = excluded.summary,
  description = excluded.description,
  image_alt = excluded.image_alt,
  display_order = excluded.display_order,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = excluded.updated_at;
